version: '3.8'

services:
  db:
    container_name: marine-postgres
    image: postgres:14
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: fastapi_admin
      POSTGRES_DB: marine
      POSTGRES_PASSWORD: fastapi_pass
  api:
    container_name: marine-backend
    build: ./marine-be
    env_file:
      - ./marine-be/.fastapi-env
    command: bash -c " alembic upgrade head & uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./marine-be:/tmp
    ports:
      - "8002:8000"
    depends_on:
      - db