version: '3.8'

services:
  db:
    container_name: marine-postgres
    image: postgres:14
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: fastapi_admin
      POSTGRES_DB: marine
      POSTGRES_PASSWORD: fastapi_pass